### ISSUE TITLE
Can't train if width does not equal height

### ISSUE THREAD

**Issue by nmddc0211** [TooTouch/MemSeg#2]
Hi TooTouch,

I tried to train your network on my custom images, whose width and height are not equal.
I get broadcasting errors if I changed the width and height in the config file. I think you have mixed up some parameters.

**Comment by tootouch** [comment]
Hi, @nmddc0211 

Thank you for sharing issue. I find the error and modify `data/dataset.py` to use the custom images, whose width and height are not equal. 

Let me know it there are any other issues.

**Comment by nmddc0211** [comment]
Thanks for replying, @TooTouch 
I am trying to fix the error myself, but it'd cool if you could also take a look.

This is what I get if I tried to train the network on my 1024x1280 (HxW) images: 
> Device: cuda:0
Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
Update 9 normal samples in memory bank
Traceback (most recent call last):
  File "/home/dangnguyen/devel/MemSeg/main.py", line 174, in <module>
    run(cfg)
  File "/home/dangnguyen/devel/MemSeg/main.py", line 148, in run
    training(
  File "/home/dangnguyen/devel/MemSeg/train.py", line 61, in training
    for inputs, masks, targets in trainloader:
  File "/home/dangnguyen/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/dangnguyen/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 692, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/dangnguyen/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dangnguyen/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dangnguyen/devel/MemSeg/data/dataset.py", line 86, in __getitem__
    img, mask = self.generate_anomaly(img=img)
  File "/home/dangnguyen/devel/MemSeg/data/dataset.py", line 156, in generate_anomaly
    anomaly_source_img = factor * (mask_expanded * anomaly_source_img) + (1 - factor) * (mask_expanded * img)
ValueError: operands could not be broadcast together with shapes (1024,1280,1) (1280,1024,3) 

I get this if DATASET.resize in yaml config file is set to 240 x 240:
Device: cuda:0
Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
Update 9 normal samples in memory bank
Traceback (most recent call last):
  File "/home/dangnguyen/devel/MemSeg/main.py", line 174, in <module>
    run(cfg)
  File "/home/dangnguyen/devel/MemSeg/main.py", line 148, in run
    training(
  File "/home/dangnguyen/devel/MemSeg/train.py", line 61, in training
    for inputs, masks, targets in trainloader:
  File "/home/dangnguyen/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/dangnguyen/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 692, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/dangnguyen/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dangnguyen/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dangnguyen/devel/MemSeg/data/dataset.py", line 86, in __getitem__
    img, mask = self.generate_anomaly(img=img)
  File "/home/dangnguyen/devel/MemSeg/data/dataset.py", line 143, in generate_anomaly
    perlin_noise_mask = self.generate_perlin_noise_mask()
  File "/home/dangnguyen/devel/MemSeg/data/dataset.py", line 182, in generate_perlin_noise_mask
    perlin_noise = rand_perlin_2d_np((self.resize[0], self.resize[1]), (perlin_scalex, perlin_scaley))
  File "/home/dangnguyen/devel/MemSeg/data/perlin.py", line 62, in rand_perlin_2d_np
    n00 = dot(tile_grads([0, -1], [0, -1]), [0, 0])
  File "/home/dangnguyen/devel/MemSeg/data/perlin.py", line 59, in <lambda>
    np.stack((grid[:shape[0], :shape[1], 0] + shift[0], grid[:shape[0], :shape[1], 1] + shift[1]),
ValueError: operands could not be broadcast together with shapes (240,240,2) (224,240,2)

**Comment by nmddc0211** [comment]
Thanks for replying, @TooTouch 
I am trying to fix the error myself, but it'd cool if you could also take a look.

This is what I get if I tried to train the network on my 1024x1280 (HxW) images, with DATASET.resize set to 1024x1280: 
> Device: cuda:0
Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
Update 9 normal samples in memory bank
Traceback (most recent call last):
  File "/home/user/devel/MemSeg/main.py", line 174, in <module>
    run(cfg)
  File "/home/user/devel/MemSeg/main.py", line 148, in run
    training(
  File "/home/user/devel/MemSeg/train.py", line 61, in training
    for inputs, masks, targets in trainloader:
  File "/home/user/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/user/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 692, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/user/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/devel/MemSeg/data/dataset.py", line 86, in __getitem__
    img, mask = self.generate_anomaly(img=img)
  File "/home/user/devel/MemSeg/data/dataset.py", line 156, in generate_anomaly
    anomaly_source_img = factor * (mask_expanded * anomaly_source_img) + (1 - factor) * (mask_expanded * img)
ValueError: operands could not be broadcast together with shapes (1024,1280,1) (1280,1024,3) 

I get this if DATASET.resize in yaml config file is set to 240x240:
>Device: cuda:0
Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
Update 9 normal samples in memory bank
Traceback (most recent call last):
  File "/home/user/devel/MemSeg/main.py", line 174, in <module>
    run(cfg)
  File "/home/user/devel/MemSeg/main.py", line 148, in run
    training(
  File "/home/user/devel/MemSeg/train.py", line 61, in training
    for inputs, masks, targets in trainloader:
  File "/home/user/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/user/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 692, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/user/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/venv/MemSeg/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/devel/MemSeg/data/dataset.py", line 86, in __getitem__
    img, mask = self.generate_anomaly(img=img)
  File "/home/user/devel/MemSeg/data/dataset.py", line 143, in generate_anomaly
    perlin_noise_mask = self.generate_perlin_noise_mask()
  File "/home/user/devel/MemSeg/data/dataset.py", line 182, in generate_perlin_noise_mask
    perlin_noise = rand_perlin_2d_np((self.resize[0], self.resize[1]), (perlin_scalex, perlin_scaley))
  File "/home/user/devel/MemSeg/data/perlin.py", line 62, in rand_perlin_2d_np
    n00 = dot(tile_grads([0, -1], [0, -1]), [0, 0])
  File "/home/user/devel/MemSeg/data/perlin.py", line 59, in <lambda>
    np.stack((grid[:shape[0], :shape[1], 0] + shift[0], grid[:shape[0], :shape[1], 1] + shift[1]),
ValueError: operands could not be broadcast together with shapes (240,240,2) (224,240,2)

**Comment by nmddc0211** [comment]
I think that did it. Thanks a lot!
